# CI: GitHub Actions workflow for automated linting and other CI on push/pull requests.
name: Frontend Integration # workflow name (shows up in GitHub Actions tab)

# GitHub will run this workflow on pushes and pull requests for the "main" (production) branch.
on:
    push:
        branches: [main] 
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    # Define a job, linting and testing coverage, to run on the GitHub Ubuntu virtual machine.
    linting-and-testing:
        runs-on: ubuntu-latest

        # Sentry DSN added via GitHub --> Settings --> Secrets --> Actions --> New repository secret
        env:
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}

        steps:
            # Check out the repo code.
            - name: Checkout code
              uses: actions/checkout@v4

            # Fail as early as possible if we don't pass the security audit to avoid exposing secrets.
            - name: Run frontend security audit
              run: node scripts/Node/security_audit.mjs

            # Install Node.js v22.14.0 in virtual environment with version 4 of setup-node in GitHub Action.
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.14.0'
                  cache: 'npm'

            # Install dependencies using specified package.json.
            - name: Install dependencies
              run: npm ci

            # Check if ESLint is running from a different working directory.
            # pwd shows current working directory. ls -la lists all files there. cat tsconfig.json prints file contents.
            - name: Debug working directory
              run: |
                pwd
                ls -la
                cat tsconfig.json

            # Run lint script.
            - name: Run ESLint
              run: npm run lint

            - name: Run Jest tests with coverage
              run: npm run test:coverage

            # Lets us view HTML report from GitHub Actions. Downloadable from actions tab.
            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                name: coverage-report
                path: coverage/lcov-report